language: php

php:
  - 7.1
  - 7.2

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 7.1
      env: setup=lowest
    - php: 7.1
      env: setup=stable
    - php: 7.2
      env: setup=lowest
    - php: 7.2
      env: setup=stable

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

before_script:
  - mkdir -p build/logs
  - travis_retry composer self-update

script: vendor/bin/phpunit

after_script: vendor/bin/coveralls -v -n
